In [49]:
import numpy as np

In [50]:
#def no_zeros(arrayInput):
    ## TODO: This function should return True if 
    ## numpy array arrayInput does not contain any zero
    ## and will return False otherwise.
    ## Implement this function using ONLY numpy methods
    ## Sample input: [1,2,3,4,5,6,0] Sample Output: False
    #return False

import numpy as np

def no_zeros(arrayInput):
    return not np.any(np.array(arrayInput) == 0)

# Test the function
sample_input = [1, 2, 3, 4, 5, 6,8,9]
result = no_zeros(sample_input)
print(result)


True


In [51]:
#def linearly_distributed(n, min, max):
    ## TODO: This function should return a numpy array of 
    ## length n with equally spaced elements from 
    ## min (inclusive) to max (exclusive)
    ## Implement this function using ONLY numpy methods
    ## Sample input: (4,0,100) sample output [0,33,66, 99]
    #return np.array({})

import numpy as np

def linearly_distributed(n, minimum, maximum):
    return np.linspace(minimum, maximum, n, endpoint=False, dtype=int)

# Test the function
sample_output = linearly_distributed(4, 0, 100)
print(sample_output)


[ 0 25 50 75]


In [52]:
#def two_dimensions(n):
    ## TODO: This function should create a 2d Array of shape n*n
    ## Where the borders of the array are ones
    ## all other elements are zero
    ## Implement this function using ONLY numpy methods
    ## Sample input 3
    ## sample output [[1,1,1],[1,0,1],[1,1,1]]
    #return np.array({})

import numpy as np

def two_dimensions(n):
    arr = np.zeros((n, n), dtype=int)
    arr[0, :] = 1  # Set the first row to ones
    arr[-1, :] = 1  # Set the last row to ones
    arr[:, 0] = 1  # Set the first column to ones
    arr[:, -1] = 1  # Set the last column to ones
    return arr

# Test the function
sample_output = two_dimensions(3)
print(sample_output)



    

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [53]:
#def create_array(n,min,max):
    ## TODO: This function should return a numpy array of 
    ## length n with random elements from 
    ## min (inclusive) to max (exclusive)
    ## Implement this function using ONLY numpy methods 
    ## USE np.random.rand for generating the numbers 
    ## Sample Input (10,0,10) sample output(0,2,2,3,1,5,9,7,8,3)
    #return np.array({})

import numpy as np

def create_array(n, minimum, maximum):
    return np.random.rand(n) * (maximum - minimum) + minimum

# Test the function
sample_output = create_array(8, 0, 8)
print(sample_output)


[3.12884116 1.74868076 2.506044   5.95478276 6.442823   6.8700347
 5.10134407 7.0073958 ]


In [54]:
#def random_generation(n,min,max):
    ## TODO: Write a function that takes as an input
    ## Dimension of 2d Array n, min and max
    ## Generate an n*n array with random numbers between
    ## min and max inclusive
    ## Such that no element is duplicated
    ## return numpy array
    ## Implement this function using ONLY numpy methods
    ## Sample Input: random_generation(3,0,12) --> [[4,2,6],[1,5,11],[10, 3,9]]
    #return np.array({})

import numpy as np

def random_generation(n, minimum, maximum):
    unique_elements = np.random.choice(np.arange(minimum, maximum + 1), size=n*n, replace=False)
    return unique_elements.reshape((n, n))

# Test the function
sample_output = random_generation(3, 3, 18)
print(sample_output)


[[10  8 14]
 [ 5  6  9]
 [11 12  4]]
