# Part A- Create a Notebook to demonstrate NumPy Operations.

# 1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [1]:
# Importing NumPy
import numpy as np

# Creating an array starting from 1, ending at 20, incremented by 3
my_array = np.arange(1, 21, 3)

# Displaying the array
print("Created NumPy Array:")
print(my_array)

Created NumPy Array:
[ 1  4  7 10 13 16 19]


# 2. Create a new array of shape 3 with random numbers between 0 and 1.

In [2]:
# Importing NumPy
import numpy as np

# Creating a new array of shape (3,) with random numbers between 0 and 1
random_array = np.random.rand(3)

# Displaying the array
print("New NumPy Array with Random Numbers between 0 and 1:")
print(random_array)

New NumPy Array with Random Numbers between 0 and 1:
[0.84093933 0.17360987 0.96028476]


# 3. Create a 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations:
   o Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows

In [3]:
# Importing NumPy
import numpy as np

# Creating a 2D array
my_2d_array = np.array([[10, 20, 45],
                        [30, 12, 16],
                        [42, 17, 56]])

# Displaying the original 2D array
print("Original 2D Array:")
print(my_2d_array)

# Slicing to get the first two rows
first_two_rows = my_2d_array[:2, :]

# Displaying the sliced array
print("\nSliced Array - First Two Rows:")
print(first_two_rows)

# Slicing to get the last two rows
last_two_rows = my_2d_array[1:, :]

# Displaying the sliced array
print("\nSliced Array - Last Two Rows:")
print(last_two_rows)


Original 2D Array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

Sliced Array - First Two Rows:
[[10 20 45]
 [30 12 16]]

Sliced Array - Last Two Rows:
[[30 12 16]
 [42 17 56]]


# 4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally,and split the arrays into smaller arrays.

In [4]:
# Importing NumPy
import numpy as np

# Creating two 2x2 arrays
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

# Displaying the original arrays
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Stack the arrays vertically
vertical_stack = np.vstack((array1, array2))

# Stack the arrays horizontally
horizontal_stack = np.hstack((array1, array2))

# Displaying the stacked arrays
print("\nVertically Stacked Array:")
print(vertical_stack)

print("\nHorizontally Stacked Array:")
print(horizontal_stack)

# Split the arrays vertically
split_vertical = np.vsplit(vertical_stack, 2)

# Split the arrays horizontally
split_horizontal = np.hsplit(horizontal_stack, 2)

# Displaying the split arrays
print("\nSplit Vertically:")
print(split_vertical)

print("\nSplit Horizontally:")
print(split_horizontal)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Vertically Stacked Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally Stacked Array:
[[1 2 5 6]
 [3 4 7 8]]

Split Vertically:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

Split Horizontally:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# 5. Create two matrices 𝑋 = ([[5, 7, 2],[4, 5, 6],[7, 4 ,2]]), 𝑌 = ([[4, 2],[6, 2],[4, 2]]),
   o Is it possible to multiply these matrices?
   o Demonstrate the case when it is not possible to.

In [5]:
# Importing NumPy
import numpy as np

# Creating matrices X and Y
X = np.array([[5, 7, 2],
              [4, 5, 6],
              [7, 4, 2]])

Y = np.array([[4, 2],
              [6, 2],
              [4, 2]])

# Displaying matrices X and Y
print("Matrix X:")
print(X)

print("\nMatrix Y:")
print(Y)

# Checking if matrix multiplication is possible
if X.shape[1] == Y.shape[0]:
    # If possible, performing matrix multiplication
    result_matrix = np.dot(X, Y)
    print("\nMatrix Multiplication Result:")
    print(result_matrix)
else:
    print("\nMatrix multiplication is not possible due to incompatible dimensions.")


Matrix X:
[[5 7 2]
 [4 5 6]
 [7 4 2]]

Matrix Y:
[[4 2]
 [6 2]
 [4 2]]

Matrix Multiplication Result:
[[70 28]
 [70 30]
 [60 26]]


# 6. Create two arrays, 𝑥 = ([2, −1, −8]) 𝑦 = ([3, 1, −2]),
o Find the Shape, Number of dimensions of vector x.

o Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions
after reshaping y to a matrix of (3,1).


In [6]:
# Importing NumPy
import numpy as np

# Creating arrays x and y
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Finding the shape and number of dimensions of vector x
shape_x = x.shape
dimensions_x = x.ndim

print("Vector x:")
print("Shape:", shape_x)
print("Number of Dimensions:", dimensions_x)

# Reshaping vector x to a matrix of size (3,1)
x_reshaped = x.reshape((3, 1))

# Finding the number of dimensions after reshaping
dimensions_x_reshaped = x_reshaped.ndim

print("\nReshaped x:")
print(x_reshaped)
print("Number of Dimensions after Reshaping:", dimensions_x_reshaped)

# Reshaping vector y to a matrix of size (3,1)
y_reshaped = y.reshape((3, 1))

# Finding the number of dimensions after reshaping
dimensions_y_reshaped = y_reshaped.ndim

print("\nReshaped y:")
print(y_reshaped)
print("Number of Dimensions after Reshaping:", dimensions_y_reshaped)


Vector x:
Shape: (3,)
Number of Dimensions: 1

Reshaped x:
[[ 2]
 [-1]
 [-8]]
Number of Dimensions after Reshaping: 2

Reshaped y:
[[ 3]
 [ 1]
 [-2]]
Number of Dimensions after Reshaping: 2


# 7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3matrix.

In [7]:
# Importing NumPy
import numpy as np

# Creating arrays x and y
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Finding the shape and number of dimensions of vector x
shape_x = x.shape
dimensions_x = x.ndim

print("Vector x:")
print("Shape:", shape_x)
print("Number of Dimensions:", dimensions_x)

# Reshaping vector x to a matrix of size (3,1)
x_reshaped = x.reshape((3, 1))

# Finding the number of dimensions after reshaping
dimensions_x_reshaped = x_reshaped.ndim

print("\nReshaped x:")
print(x_reshaped)
print("Number of Dimensions after Reshaping:", dimensions_x_reshaped)

# Reshaping vector y to a matrix of size (3,1)
y_reshaped = y.reshape((3, 1))

# Finding the number of dimensions after reshaping
dimensions_y_reshaped = y_reshaped.ndim

print("\nReshaped y:")
print(y_reshaped)
print("Number of Dimensions after Reshaping:", dimensions_y_reshaped)


Vector x:
Shape: (3,)
Number of Dimensions: 1

Reshaped x:
[[ 2]
 [-1]
 [-8]]
Number of Dimensions after Reshaping: 2

Reshaped y:
[[ 3]
 [ 1]
 [-2]]
Number of Dimensions after Reshaping: 2


# PART B - Linear Equations 

Determine the singularity of the system of equations, comment on the expected solution of the system.
Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be
solved using NumPy functions.

# Part B.1

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

In [8]:
# Importing NumPy
import numpy as np

# Coefficient matrix for the system
A = np.array([[4, 1, -2],
               [2, -3, 2],
               [1, 2, 3]])

# Calculating determinant
det_A = np.linalg.det(A)

print("Determinant of Matrix A:", det_A)

# Solving the system if the determinant is non-zero
if det_A != 0:
    solution = np.linalg.solve(A, [10, -4, 6])
    print("Solution for the System:", solution)
else:
    print("The system is singular (det(A) = 0), and a unique solution may not exist.")


Determinant of Matrix A: -70.00000000000003
Solution for the System: [ 1.8  2.4 -0.2]


# Part B.2

1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1


In [9]:
# Importing NumPy
import numpy as np

# Coefficient matrix for the system
A = np.array([[2, -1, 3, 4],
               [4, -2, 6, 8],
               [3, 1, -2, 2],
               [1, 3, -4, 1]])

# Calculating determinant
det_A = np.linalg.det(A)

print("Determinant of Matrix A:", det_A)

# Solving the system if the determinant is non-zero
if det_A != 0:
    solution = np.linalg.solve(A, [10, 20, 3, -1])
    print("\nSolution for the System:", solution)
else:
    print("\nThe system is singular (det(A) = 0), and a unique solution may not exist.")


Determinant of Matrix A: 0.0

The system is singular (det(A) = 0), and a unique solution may not exist.
